language: go

# safelist
branches:
  only:
  - master

before_install:
  - go get -d github.com/onsi/gomega
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/modocache/gover
  - go get -d github.com/eawsy/aws-lambda-go-event/...
  - go get -d github.com/eawsy/aws-lambda-go-core/service/lambda/runtime

script:
  - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --trace --race --compilers=2 --coverpkg github.com/Morras/neutrinoapi

after_success:
  - gover . coverage.txt
  - bash <(curl -s https://codecov.io/bash)